// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKs2A9_6MgPmjbI-rPq8hirPyXdSU0rbw',
    appId: '1:1003135821325:android:a34895547294589ed91744',
    messagingSenderId: '1003135821325',
    projectId: 'fakechats-zz',
    storageBucket: 'fakechats-zz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5MbM71BYXGD_ev9sUv_6KrAWr4qGjCI',
    appId: '1:1003135821325:ios:9894065c3120415ad91744',
    messagingSenderId: '1003135821325',
    projectId: 'fakechats-zz',
    storageBucket: 'fakechats-zz.appspot.com',
    androidClientId: '1003135821325-fs3eos8ql6670nramoan2al7efrfq74t.apps.googleusercontent.com',
    iosClientId: '1003135821325-vt8ipb0jl50d7b12cltkfjo17q2dm1bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.messages',
  );

}